# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\searchv1.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_search(object):
    def setupUi(self, search):
        search.setObjectName("search")
        search.resize(863, 655)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        search.setFont(font)
        self.model_box = QtWidgets.QGroupBox(search)
        self.model_box.setGeometry(QtCore.QRect(20, 10, 151, 221))
        self.model_box.setObjectName("model_box")
        self.layoutWidget = QtWidgets.QWidget(self.model_box)
        self.layoutWidget.setGeometry(QtCore.QRect(7, 30, 131, 191))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.SB_button = QtWidgets.QRadioButton(self.layoutWidget)
        self.SB_button.setChecked(True)
        self.SB_button.setObjectName("SB_button")
        self.verticalLayout.addWidget(self.SB_button)
        self.SBL_button = QtWidgets.QRadioButton(self.layoutWidget)
        self.SBL_button.setObjectName("SBL_button")
        self.verticalLayout.addWidget(self.SBL_button)
        self.WQ_button = QtWidgets.QRadioButton(self.layoutWidget)
        self.WQ_button.setObjectName("WQ_button")
        self.verticalLayout.addWidget(self.WQ_button)
        self.xiaofang_button = QtWidgets.QRadioButton(self.layoutWidget)
        self.xiaofang_button.setObjectName("xiaofang_button")
        self.verticalLayout.addWidget(self.xiaofang_button)
        self.wenya_button = QtWidgets.QRadioButton(self.layoutWidget)
        self.wenya_button.setObjectName("wenya_button")
        self.verticalLayout.addWidget(self.wenya_button)
        self.type_box = QtWidgets.QGroupBox(search)
        self.type_box.setGeometry(QtCore.QRect(220, 10, 161, 221))
        self.type_box.setObjectName("type_box")
        self.layoutWidget1 = QtWidgets.QWidget(self.type_box)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 30, 121, 105))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.precise_button = QtWidgets.QRadioButton(self.layoutWidget1)
        self.precise_button.setChecked(True)
        self.precise_button.setObjectName("precise_button")
        self.verticalLayout_2.addWidget(self.precise_button)
        self.fuzzy_button = QtWidgets.QRadioButton(self.layoutWidget1)
        self.fuzzy_button.setObjectName("fuzzy_button")
        self.verticalLayout_2.addWidget(self.fuzzy_button)
        self.parameter_box = QtWidgets.QGroupBox(search)
        self.parameter_box.setGeometry(QtCore.QRect(430, 10, 161, 221))
        self.parameter_box.setObjectName("parameter_box")
        self.layoutWidget2 = QtWidgets.QWidget(self.parameter_box)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 40, 141, 79))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.flow_label = QtWidgets.QLabel(self.layoutWidget2)
        self.flow_label.setObjectName("flow_label")
        self.horizontalLayout_2.addWidget(self.flow_label)
        self.flow_input = QtWidgets.QLineEdit(self.layoutWidget2)
        self.flow_input.setObjectName("flow_input")
        self.horizontalLayout_2.addWidget(self.flow_input)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lift_label = QtWidgets.QLabel(self.layoutWidget2)
        self.lift_label.setObjectName("lift_label")
        self.horizontalLayout_3.addWidget(self.lift_label)
        self.lift_input = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lift_input.setObjectName("lift_input")
        self.horizontalLayout_3.addWidget(self.lift_input)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.result_box = QtWidgets.QGroupBox(search)
        self.result_box.setGeometry(QtCore.QRect(20, 240, 831, 411))
        self.result_box.setObjectName("result_box")
        self.result_text = QtWidgets.QTextBrowser(self.result_box)
        self.result_text.setGeometry(QtCore.QRect(10, 50, 811, 351))
        self.result_text.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.result_text.setFont(font)
        self.result_text.setObjectName("result_text")
        self.danwei = QtWidgets.QLabel(self.result_box)
        self.danwei.setGeometry(QtCore.QRect(140, 10, 561, 41))
        self.danwei.setObjectName("danwei")
        self.layoutWidget3 = QtWidgets.QWidget(search)
        self.layoutWidget3.setGeometry(QtCore.QRect(650, 20, 141, 211))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.search_button = QtWidgets.QPushButton(self.layoutWidget3)
        self.search_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.search_button.setIconSize(QtCore.QSize(20, 20))
        self.search_button.setObjectName("search_button")
        self.verticalLayout_4.addWidget(self.search_button)
        self.clear_button = QtWidgets.QPushButton(self.layoutWidget3)
        self.clear_button.setObjectName("clear_button")
        self.verticalLayout_4.addWidget(self.clear_button)

        self.retranslateUi(search)
        QtCore.QMetaObject.connectSlotsByName(search)

    def retranslateUi(self, search):
        _translate = QtCore.QCoreApplication.translate
        search.setWindowTitle(_translate("search", "型号检索系统（昆山赛特斯流体设备有限公司）"))
        self.model_box.setTitle(_translate("search", "型号"))
        self.SB_button.setText(_translate("search", "卧式泵"))
        self.SBL_button.setText(_translate("search", "立式泵"))
        self.WQ_button.setText(_translate("search", "污水泵"))
        self.xiaofang_button.setText(_translate("search", "消防"))
        self.wenya_button.setText(_translate("search", "消防稳压"))
        self.type_box.setTitle(_translate("search", "检索方式"))
        self.precise_button.setText(_translate("search", "精确查找"))
        self.fuzzy_button.setText(_translate("search", "模糊查找"))
        self.parameter_box.setTitle(_translate("search", "输入参数"))
        self.flow_label.setText(_translate("search", "流量"))
        self.lift_label.setText(_translate("search", "扬程"))
        self.result_box.setTitle(_translate("search", "检索结果"))
        self.danwei.setText(_translate("search", "单位：流量(m³/h)，扬程(m)，转速(r/min)，功率(kW)"))
        self.search_button.setText(_translate("search", "检索"))
        self.clear_button.setText(_translate("search", "清空"))


